/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java project to get you started.
 * For more details take a look at the Java Quickstart chapter in the Gradle
 * User Manual available at https://docs.gradle.org/6.4/userguide/tutorial_java_projects.html
 */

plugins {
    // Apply the java plugin to add support for Java
    java

    // Apply the application plugin to add support for building a CLI application.
    application
}

repositories {
    // Use jcenter for resolving dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
}

val jmeterVersion = "5.1.1"
val slf4jVersion = "1.7.30"

dependencies {
    implementation(group = "org.apache.jmeter", name = "ApacheJMeter_java", version = jmeterVersion)
    implementation(platform("org.apache.jmeter:ApacheJMeter_parent:$jmeterVersion"))

    implementation(group = "org.slf4j", name = "slf4j-api", version = slf4jVersion)

    testImplementation("org.junit.jupiter:junit-jupiter-api:5.6.0")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.6.0")
}

application {
    // Define the main class for the application.
    mainClassName = "dgroomes.App"
}

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}
